### ISSUE TITLE
create UI tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-hello#27]
- [x] find a selenium - gherkin - go stack #76 
- [x] implement a starting point for UI tests #76
- [x] run tests in drone WIP #75

**Comment by individual-it** [comment]
The important integration parts of Phoenix aren't done yet, so its not possible to test the UI of the app yet

CC @micbar @tboerger

**Comment by micbar** [comment]
@individual-it @tboerger Correct.
According to @PVince81 we will be there as soon as the split of phoenix is ready.
